cargo-features = ["profile-rustflags"]

[package]
name = "wasm_assessment"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
wasm_multithread = []

[dependencies]
chrono = "0.4.31"
parquet2 = "0.17.2"
rayon = "1.8.0"
